[package]
name = "raspi_monitor"
version = "0.1.0"
authors = ["pegasis <admin@pegasis.site>"]
edition = "2018"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[dependencies]
systemstat = "0.1.5"
failure = "0.1.8"
json_minimal = "0.1.1"
fs2 = "0.4.3"
